package org.herac.tuxguitar.song.models;

public interface TGVelocities {

	int MIN_VELOCITY = 15;
	int VELOCITY_INCREMENT = 16;
	int PIANO_PIANISSIMO = (MIN_VELOCITY);
	int PIANISSIMO = (MIN_VELOCITY + VELOCITY_INCREMENT);
	int PIANO = (MIN_VELOCITY + (VELOCITY_INCREMENT * 2));
	int MEZZO_PIANO = (MIN_VELOCITY + (VELOCITY_INCREMENT * 3));
	int MEZZO_FORTE = (MIN_VELOCITY + (VELOCITY_INCREMENT * 4));
	int FORTE = (MIN_VELOCITY + (VELOCITY_INCREMENT * 5));
	int FORTISSIMO = (MIN_VELOCITY + (VELOCITY_INCREMENT * 6));
	int FORTE_FORTISSIMO = (MIN_VELOCITY + (VELOCITY_INCREMENT * 7));
	int DEFAULT = FORTE;

}
